# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-09-09 06:48
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('text_exp', '0003_auto_20200909_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='failed_intro_test',
            field=otree.db.models.BooleanField(choices=[(True, True), (False, False)], default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='instruction_timeout',
            field=otree.db.models.BooleanField(choices=[(True, True), (False, False)], default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='pass_intro_test',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
