# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-09-09 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_exp', '0004_auto_20200909_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='failed_intro_test',
        ),
        migrations.RemoveField(
            model_name='player',
            name='instruction_timeout',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pass_intro_test',
        ),
    ]
